# In .github/workflows/auto_build_immich.yml

name: Check for New Immich Version

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  Check-and-prepare:
    runs-on: ubuntu-latest
    outputs:
      latest_release: ${{ steps.check.outputs.latest_release }}
      is_new_release: ${{ steps.compare.outputs.is_new_release }}
    steps:
      - name: Get latest Immich release
        id: check
        run: |
          LATEST_TAG=$(curl -sL https://api.github.com/repos/immich-app/immich/releases/latest | jq -r '.tag_name')
          if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" == "null" ]; then
            echo "Failed to fetch latest release tag. Exiting."
            exit 1
          fi
          echo "latest_release=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Compare latest release with stored one
        id: compare
        env:
          STORED_RELEASE_VAR: ${{ vars.LATEST_IMMICH_RELEASE }}
        run: |
          LATEST_TAG=${{ steps.check.outputs.latest_release }}
          PREV_TAG="${{ env.STORED_RELEASE_VAR }}"
          echo "Latest tag: $LATEST_TAG"
          echo "Previous tag (from variable): $PREV_TAG"
          if [ "$LATEST_TAG" != "$PREV_TAG" ]; then
            echo "is_new_release=true" >> $GITHUB_OUTPUT
            echo "::notice::New release detected: $LATEST_TAG."
          else
            echo "is_new_release=false" >> $GITHUB_OUTPUT
            echo "::notice::No new release detected."
          fi

      - name: Save parameters to artifact
        run: |
          mkdir -p run-parameters
          echo "${{ steps.check.outputs.latest_release }}" > run-parameters/version.txt
          echo "${{ steps.compare.outputs.is_new_release }}" > run-parameters/is_new_release.txt
      
      - name: Upload parameters artifact
        uses: actions/upload-artifact@v4
        with:
          name: run-parameters
          path: run-parameters/