name: Check for New Immich Version and Trigger Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  Check-immich-release:
    runs-on: ubuntu-latest
    outputs:
      latest_release: ${{ steps.check.outputs.latest_release }}
      is_new_release: ${{ steps.compare.outputs.is_new_release }}
    steps:
      - name: Get latest Immich release
        id: check
        run: |
          LATEST_TAG=$(curl -sL https://api.github.com/repos/immich-app/immich/releases/latest | jq -r '.tag_name')
          # Handle case where tag is not found
          if [ -z "$LATEST_TAG" ] || [ "$LATEST_TAG" == "null" ]; then
            echo "Failed to fetch latest release tag."
            exit 1
          fi
          echo "latest_release=$LATEST_TAG" >> $GITHUB_OUTPUT

      - name: Compare latest release with stored one
        id: compare
        env:
          STORED_RELEASE_VAR: ${{ vars.LATEST_IMMICH_RELEASE }}
        run: |
          LATEST_TAG=${{ steps.check.outputs.latest_release }}
          PREV_TAG="${{ env.STORED_RELEASE_VAR }}"
          echo "Latest tag: $LATEST_TAG"
          echo "Previous tag (from variable): $PREV_TAG"
          if [ "$LATEST_TAG" != "$PREV_TAG" ]; then
            echo "is_new_release=true" >> $GITHUB_OUTPUT
            echo "::notice::New release detected: $LATEST_TAG. Build will proceed."
          else
            echo "is_new_release=false" >> $GITHUB_OUTPUT
            echo "::notice::No new release detected. Manual build will proceed if triggered."
          fi

  Trigger-Build-Chain:
    needs: Check-immich-release
    runs-on: ubuntu-latest
    # This job runs if a new release is found OR if the workflow was manually dispatched.
    if: ${{ needs.Check-immich-release.outputs.is_new_release == 'true' || github.event_name == 'workflow_dispatch' }}
    steps:
      - name: Trigger build_dependencies workflow
        env:
          GITHUB_TOKEN: ${{ secrets.ACTIONS_PAT }}
          LATEST_TAG: ${{ needs.Check-immich-release.outputs.latest_release }}
          IS_NEW_RELEASE: ${{ needs.Check-immich-release.outputs.is_new_release }}
        run: |
          # If manually triggered, LATEST_TAG might be empty. Use the one from the check job.
          # For a manual run, we always treat it as a "new release" for building purposes.
          VERSION_TO_BUILD="${{ github.event.inputs.version || env.LATEST_TAG }}"
          SHOULD_RELEASE="${{ (github.event_name == 'workflow_dispatch') && 'false' || env.IS_NEW_RELEASE }}"

          echo "Triggering build for version $VERSION_TO_BUILD"
          echo "Is new release flag set to: $SHOULD_RELEASE"

          gh workflow run build_dependencies.yml --ref ${{ github.ref_name }} -f version="$VERSION_TO_BUILD" -f is_new_release="$SHOULD_RELEASE"