name: Build Immich on New Release

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-immich-release:
    runs-on: ubuntu-latest
    outputs:
      latest_release: ${{ steps.check.outputs.latest_release }}
      is_new_release: ${{ steps.check.outputs.is_new_release }}
    steps:
      - name: Restore previous release tag
        id: cache
        uses: actions/cache@v4
        with:
          path: .latest_immich_release
          key: immich-latest-release

      - name: Get latest Immich release
        id: check
        run: |
          LATEST_TAG=$(curl -s https://api.github.com/repos/immich-app/immich/releases/latest | jq -r '.tag_name')
          PREV_TAG=$(cat .latest_immich_release 2>/dev/null || echo "")
          echo "latest_release=$LATEST_TAG" >> $GITHUB_ENV
          echo "latest_release=$LATEST_TAG" >> $GITHUB_OUTPUT
          if [ "$LATEST_TAG" != "$PREV_TAG" ]; then
            echo "is_new_release=true" >> $GITHUB_ENV
            echo "is_new_release=true" >> $GITHUB_OUTPUT
            echo "$LATEST_TAG" > .latest_immich_release
          else
            echo "is_new_release=false" >> $GITHUB_ENV
            echo "is_new_release=false" >> $GITHUB_OUTPUT
          fi

      - name: Save latest release tag
        if: steps.check.outputs.is_new_release == 'true'
        uses: actions/cache@v4
        with:
          path: .latest_immich_release
          key: immich-latest-release

  Build-immich:
    needs: check-immich-release
    if: needs.check-immich-release.outputs.is_new_release == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync with upstream loeeeee/immich-in-lxc
        run: |
          git remote add upstream https://github.com/loeeeee/immich-in-lxc.git || true
          git fetch upstream
          git checkout main
          git merge --ff-only upstream/main || echo "Already up-to-date"
          git push origin main || echo "No changes to push"
          
      - name: Set up Node.js
        uses: actions/setup-node@v4.3.0
        with:
          node-version: '20'
          
      - name: Install Jellyfin ffmpeg
        run: |
          sudo apt install curl gnupg software-properties-common
          sudo add-apt-repository universe
          sudo mkdir -p /etc/apt/keyrings
          curl -fsSL https://repo.jellyfin.org/jellyfin_team.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/jellyfin.gpg
          export VERSION_OS="$( awk -F'=' '/^ID=/{ print $NF }' /etc/os-release )"
          export VERSION_CODENAME="$( awk -F'=' '/^VERSION_CODENAME=/{ print $NF }' /etc/os-release )"
          export DPKG_ARCHITECTURE="$( dpkg --print-architecture )"
          cat <<-EOF | sudo tee /etc/apt/sources.list.d/jellyfin.sources
          Types: deb
          URIs: https://repo.jellyfin.org/${VERSION_OS}
          Suites: ${VERSION_CODENAME}
          Components: main
          Architectures: ${DPKG_ARCHITECTURE}
          Signed-By: /etc/apt/keyrings/jellyfin.gpg
          EOF
          sudo apt update
          sudo apt install jellyfin-ffmpeg7
          sudo ln -s /usr/lib/jellyfin-ffmpeg/ffmpeg  /usr/bin/ffmpeg
          sudo ln -s /usr/lib/jellyfin-ffmpeg/ffprobe  /usr/bin/ffprobe

      - name: Install Python 3.11
        run: |
          # install Python 3.11
          # before onnxruntime-openvino is bumped, we can only use Python 3.11
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install -y python3.11 python3.11-venv python3.11-dev
          # overwrite the default Python version
          sudo ln -sf /usr/bin/python3.11 /usr/bin/python3

      - name: Pre-build
        env:
          IMMICH_VERSION: ${{ needs.check-immich-release.outputs.latest_release }}
        run: |
          UPLOAD_DIR=/mnt/photos/.immich
          sudo mkdir -p $UPLOAD_DIR
          cd ${{ github.workspace }}
          sudo ./dep-ubuntu.sh
          sudo ./pre-install.sh
          # create .env
          cat << EOF > .env
          REPO_TAG=$IMMICH_VERSION
          INSTALL_DIR=/home/runner
          UPLOAD_DIR=$UPLOAD_DIR
          isCUDA=openvino
          PROXY_NPM=
          PROXY_POETRY=
          EOF
          
      - name: Build immich server
        run: |
          ./install.sh 

      - name: Archive app folder
        run: |
          tar -czf app.tar.gz -C ~/app .

      - name: Upload app as artifact
        uses: actions/upload-artifact@v4
        with:
          name: immich-app-${{ needs.check-immich-release.outputs.latest_release }}
          path: app.tar.gz
